### PR TITLE
feat:🎁 nuget search

### PR DESCRIPTION
**Pull request by GustavEikaas**
vim: `Dotnet add package`
lua: `dotnet.add_package()`

Gives you a telescope picker for searching nuget packages, upon selecting a a package you will be given a new picker for which version to install. Lastly you will get a picker for which project to add to

1. Search package
2. Select version
3. Select project to add to

image

### CODE REVIEW

**Comment by GustavEikaas** [comment]
@cbosvik I dabbled a bit. Would you want to try it out?

**Comment by cbosvik** [comment]
absolutely! need to digest the ”kransekake” first though😂

**Comment by GustavEikaas** [comment]
@cbosvik Lets not agitate your wife any further!

**Comment by cbosvik** [comment]
@GustavEikaas Great work! I do get errors from the picker after selecting version if I did not explicitly select the sln first(or opened a file in the project). Also there is a slight lag in the picker, when filtering packages. Other than that it works really well🥳

**Comment by GustavEikaas** [comment]
I fixed the issues with the sln picker. The lag in the picker is a bigger issue unfortunately. I implemented it first with fzf and that worked really well, when I ported it to telescope it wasnt the same. I'm not an expert in telescope so maybe there is a better way to do it, im not sure

**Pull request merged**
