### PR TITLE
feat: try to support neovim 0.9.5

### PR DESCRIPTION
**Pull request by GustavEikaas**
Unavailable commands

- `vim.iter`
- `vim.tbl_x`
- `vim.fs.joinpath`

### CODE REVIEW

**Comment by jorgevds** [comment]
Hey,

Not sure if you're accepting unsolicited advice, but what do you think about creating a polyfill module that does the same thing as the functions you're replacing? Would probably save a bit of time if you can accurately polyfill the functions. And then if you ever need to migrate to a higher neovim version, you could just reassign the functions to be the neovim builtin ones. WDYT?

**Comment by GustavEikaas** [comment]
I love unsolicited advice! Yeah you beat me to it, I was thinking of doing just that

**Comment by jorgevds** [comment]
Lmao sorry 😂

**Comment by GustavEikaas** [comment]
Haha, it was a good suggestion!

**Comment by GustavEikaas** [comment]
Superceeded by #206

**Pull request closed without merging**
