### PR TITLE
feat:🎁 testrunner tree structure 

### PR DESCRIPTION
**Pull request by GustavEikaas**
## Description
Previously the testrunner had the test hieararchy represented as a flat list internally, this was suboptimal making the feature request #173 hard to implement, amongst other things. In this PR I will convert this into a recursive tree structure which will hopefully improve maintainability, readability and making features easier to develop.

## Feature parity
- [x] Make tree 
- [x] Render tree
- [x] Keymaps
  - [x] Close
  - [x] Refresh
  - [x] Debug test
  - [x] Go to file
  - [x] Expand all
  - [x] Collapse all
  - [x] Filter failed tests
  - [x] Expand
  - [x] Peek stacktrace
  - [x] Run all tests
  - [x] Run test
- [x] Highlights
- [x] Run test from buffer
- [x] Debug test from buffer
- [x] Status aggregation in tree
- [x] Virtual text
- [x] Filter
- [x] Status in gutter
- [x] Gutter sign lookup

Stacktrace propagating to ancestor? (is this used?)

## New features/improvements

- Test counting #173 
- Expanded/collapsed nodes remember their state when being hidden/shown by a parent
- Keybind for expanding node recursively
- Deterministic sorting
- ignore test projects with 0 children
- add cursorline to buffer

### CODE REVIEW

**Comment by GustavEikaas** [comment]
@molostovvs Would you be interested in testing this branch? 
I rewrote the entire thing to use a tree structure so I very well might have broken some existing functionality, hopefully not though. PR is not 100% finished but everything except filtering failed tests should work. Including the new feature of test counting as mentioned in #173 

Any feedback would be greatly appreciated

**Comment by GustavEikaas** [comment]
@AjayKMehta Feel free to test it aswell, any feedback is good feedback

**Comment by AjayKMehta** [comment]
> @AjayKMehta Feel free to test it aswell, any feedback is good feedback

I will try my best. I have been swamped lately which is why I have not been as involved like I was ~ 2 months ago. I only recently got around to installing this plugin (and `roslyn.nvim`) and must say, you did an amazing job, @Gustav-Eikaas! 👏

**Comment by GustavEikaas** [comment]
Ah no worries man, only test if you have time to spare no pressure! :D

**Pull request merged**
