### PR TITLE
feat: add configurability to icons

### PR DESCRIPTION
**Pull request by adriankarlen**
Made icons configurable via options.

First draft, have not been able to test it properly yet, but if desired I'll look in to it more. Solves #131.

### CODE REVIEW

**Comment by GustavEikaas** [comment]
Looks good so far, this looks like something I would accept. Some thoughts just for information. I have been thinking that things like the sln icon should not be attached to the object itself but derived from the `type` field. 

Im pretty sure the initial state of the testrunner is no longer valid so the refresh icon is never used. 

The default icons were like a best effort from my side to find some suitable icons. Id be interested in seeing what icons you would use and maybe make those the defaults

But anyways, awesome PR! Let me know when you want me to test it and review it, looks good so far

**Comment by adriankarlen** [comment]
Yeah, reasonable thoughts. My first idea was simply to use nerdfont-icons for everything, to streamline it. Like this:
image
image
image

**Comment by GustavEikaas** [comment]
Had to make a couple of small changes, I just wrote a simple merge_table early in the project without knowing of the vim deep extend. It was not an issue because there were no nested structures. I just added that fix here because if a user specifices a single icon they want to override the other icons become nil. 

Would you mind updating the readme to inform that customizing icons is an option?

**Comment by adriankarlen** [comment]
> Dependency injection? huh?

Yeah, sorry about the confusion, it was late here when I wrote it. What I meant was that the way the options were being passed parameters felt a bit clunky.

**Comment by adriankarlen** [comment]
> Had to make a couple of small changes, I just wrote a simple merge_table early in the project without knowing of the vim deep extend. It was not an issue at the time because there were no nested structures. I just added that fix here because if a user specifices a single icon they want to override the other icons become nil. 
> 
> 
> 
> Would you mind updating the readme to inform that customizing icons is an option?

Yes, will do. What is your opinion regarding the defaults?

**Comment by GustavEikaas** [comment]
Im a little skeptical to the skipped icon, is it intuitive enough? Maybe
But your defaults are definitely better than the current ones so please do update them with yours. 

yeah passing around options seems weird but I still havent seen any nvim plugins with better ways to do it. Using `vim.g` is a no-go for me

**Comment by adriankarlen** [comment]
> Im a little skeptical to the skipped icon, is it intuitive enough? Maybe But your defaults are definitely better than the current ones so please do update them with yours.

I agree on the skip icon, I did not put that much time in to selecting icons, it was mostly for testing.

I thinkthe following selection would look nice as defaults, everything except the cs-logo uses octicons, seems like it would provide a nice default look.
image

**Comment by GustavEikaas** [comment]
Sold! #shipit

**Comment by adriankarlen** [comment]
Updated the defaults and added them to the readme, I did not however change the screenshots of the testrunner, as I don't have a public project to give an example of.

**Comment by GustavEikaas** [comment]
image
Looks amazing! Great work!

What do you think, are we ready to merge?
The code looks good, I tested it and it works, there is no breaking changes, shipit?

One thing I noticed is that the default icons doesnt render for me in github markdown so im guessing the readme for most people will have `?` for every icon. I dont know if people are using nerdfonts in their browsers idk, im fine with it so I guess we can merge?

**Review by GustavEikaas — APPROVED** [review]

**Comment by adriankarlen** [comment]
Yeah the nerd font thing is inevitable I'd say. Go ahead and merge it! :)

**Comment by GustavEikaas** [comment]
@adriankarlen Amazing work!❤ Thank you for contributing! 😁

**Pull request merged**
