### PR TITLE
feat: configurable highlight groups

### PR DESCRIPTION
**Pull request by adriankarlen**
After the icon change I realized it would be nice to be able to control the highlight groups a bit more, this PR adds more `EasyDotnet`-highlights for the user to configure.

They all default to groups that should be set by default in the users theme.

I also went a head and used the `Diagnostic`-highlights for the test-status.

If you think this is a nice addition I'll add information to the readme. I've always liked folkes way of showcasing highlights in the readme via a collapsable table at the bottom of the readme, thoughts on that?

### CODE REVIEW

**Comment by GustavEikaas** [comment]
Looks great!🤩 Awesome work, yes please go ahead with readme update.

Note;
Probably time to extract the hl declarations into a separate function.

**Review by GustavEikaas — APPROVED** [review]
Awesome work!

**Comment by GustavEikaas** [comment]
Code looks great, just update the readme and we are ready to merge. Im not sure im familiar with folkes way of doing it but im sure ill like it so please give it a go

**Comment by adriankarlen** [comment]
Okay, so I've added the highlights to the readme

**Comment by GustavEikaas** [comment]
PR looks good, maybe we can add a default color to tests aswell?

Im thinking we should maybe make a highlight group for subcases. I think it would be interesting to use `Conceal` for those as they cannot be run directly, you have to run the package. Thoughts?

**Comment by adriankarlen** [comment]
Agreed would be good!

**Review by GustavEikaas — APPROVED** [review]

**Comment by GustavEikaas** [comment]
LGTM shipit🚀?

**Comment by adriankarlen** [comment]
Go ahead!

**Comment by GustavEikaas** [comment]
Awesome work! ♥

**Pull request merged**
