### PR TITLE
feat: support for neovim 0.9.5

### PR DESCRIPTION
**Pull request by GustavEikaas**

### CODE REVIEW

**Comment by GustavEikaas** [comment]
@jorgevds it works on my machine now on nvim 0.9.5. Would you want to test this branch?

**Comment by jorgevds** [comment]
@GustavEikaas It works! But I am seeing the testrunner now as the following:

Screenshot 2024-12-22 at 19 52 02

On neovim 0.10.2 it looked like in the screenshot in the readme. Not sure if this is intended?

**Comment by GustavEikaas** [comment]
Strange mine looks nice on 0.9.5
image

**Comment by jorgevds** [comment]
Retried with the "with options" example and I did get the float now. I didn't know there were different options.

Screenshot 2024-12-22 at 20 04 02

And I won't be accepting the shade you're throwing towards my Kanagawa theme, tyvm.

**Comment by GustavEikaas** [comment]
Haha im sorry! I didnt understand what you were pointing towards! As long as its a dark theme I wont be throwing any shade

So everything works as expected for you?

**Comment by jorgevds** [comment]
No errors on install, got "run" to work, and the testrunner looks a m a z i n g !

Tested OK for me! Thank you very much!

**Pull request merged**
